api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'domains/',
        views.DomainListView.as_view(),
        name="domain-list-api"),
    path(
        'my-domains/',
        views.UsersDomainsListView.as_view(),
        name="my-domain-list-api"),
    path(
        'brainstorming/',
        views.DomainBrainStormingAPIView.as_view(),
        name="brainstorming-api"
    ),
    path(
        'domains/<int:pk>/',
        views.SingleDomainAPIView.as_view(),
        name="single-domain-api"),
    path(
        'autocomplete/',
        views.SearchAutoCompleteView.as_view(),
        name="autocomplete-api"),
    path(
        'favourite/',
        views.FavouriteAPIView.as_view(),
        name="favourite-api"),
    path(
        'contacts/',
        views.ContactsAPIView.as_view(),
        name="contact-api"),
    path(
        'negotiate/',
        views.NegotiateContactAPIView.as_view(),
        name="negotiate-api"),
    path(
        'appraisal/',
        views.DomainAppraisalAPIView.as_view(),
        name="domain-appraisal"),
    path(
        'verify/',
        views.VerifyDomainAPIView.as_view(),
        name="verify-domain-redirect"
    ),
]

brandpulsar/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('v1/api/', include('rest_framework.urls')),
    path('v1/api/', include('api.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path
from . import views

app_name='marketplace'

urlpatterns = [
    path('become-a-seller/', views.BecomeASellerView.as_view(), name='become-a-seller'),
    path('create/', views.DomainCreateView.as_view(), name='create-domain'),
    path('setup/<int:pk>/', views.DomainSetupView.as_view(), name='setup-domain'),
    path('update/<int:pk>/', views.DomainUpdateView.as_view(), name='update-domain'),
    path('delete/<int:pk>/', views.DomainDeleteView.as_view(), name='delete-domain'),
    path('brainstorming/', views.BrainStormingView.as_view(), name="brainstorming-view"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register-view"),
    path('activate/', views.ActivateView.as_view(), name="register-done-view"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('activate/<uidb64>/<token>/',
         views.ActivateView.as_view(),
         name="activate-view"),
    path('login/', views.LoginView.as_view(), name="login-view"),
    path('logout/', views.LogOutView.as_view(), name="logout-view"),
    path(
        'password/reset/',
        views.CustomPasswordResetView.as_view(),
        name="password-reset"),
    path(
        'password/confirm/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path(
        'password/done/',
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_complete"),
    path('edit/',
         login_required(views.UserEditView.as_view()),
         name="user-edit-view"),
    path('edit/password/',
         login_required(views.UserPasswordEditView.as_view()),
         name="user-edit-password-view"),
    # path(
    #     'payment-methods/',
    #     views.PaymentMethodListView.as_view(),
    #     name="payment-method-list"
    # ),
    # path(
    #    'add/payment-method/',
    #    views.PaymentMethodCreateView.as_view(),
    #    name="add-payment-method"
    # ),
    # path(
    #    'update/payment-method/<int:pk>/',
    #    views.PaymentMethodUpdateView.as_view(),
    #    name="update-payment-method"
    # ),
    # path(
    #    'delete/payment-method/<int:pk>/',
    #    views.PaymentMethodDeleteView.as_view(),
    #    name="delete-payment-method",
    # ),
    # path('payment-history/', views.PaymentHistoryView.as_view(),
    #      name="payment-history",)
]

main/models.py
import random
import uuid as uuid
import stripe
import syllables
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save, pre_save
from treebeard.mp_tree import MP_Node
from main.managers import RecentBlogPostManager
from main.utils import get_file_path
from brandpulsar.utils import compress_image, disable_for_loaddata

User = get_user_model()


class Industry(MP_Node):
    name = models.CharField(
        _("Industry name"),
        max_length=100
    )
    featured = models.BooleanField(
        _("Featured"),
        default=False
    )
    icon = models.FileField(_("Icon"), null=True, blank=True, upload_to='industries/%Y/%m/%d/')
    slug = models.SlugField(
        _("Industry slug"),
        null=True,
        blank=True,
        default=None,
        max_length=50
    )
    content = RichTextUploadingField(
        null=True, blank=True
    )
    date_updated = models.DateTimeField(
        auto_now=True, null=True
    )
    date_created = models.DateTimeField(
        auto_now_add=True
    )
    node_order_by = ['name']

    objects = models.Manager()

    def featured_item(self):
        # Returns most expensive related domain item for object
        return self.industry.order_by('-price').first()

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.name)[:50]
            duplicate = Industry.objects.filter(slug=slug).first()
            if not duplicate:
                self.slug = slug
            else:
                self.slug = f"{slug}-{random.randint(1, 10)}"
        super(Industry, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('main:industry-detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Industry"
        verbose_name_plural = "Industries"

    def __str__(self):
        return self.name


class Tag(models.Model):
    title = models.CharField(_("Domain tag title"), max_length=250)

    def __str__(self):
        return self.title


class Plan(models.Model):
    domain = models.ForeignKey(
        "main.Domain",
        on_delete=models.CASCADE,
        related_name="plans",
        null=True)
    nickname = models.CharField(
        _("Plan Nickname"),
        max_length=50
    )
    unit_amount = models.DecimalField(
        _("Price per unit"),
        decimal_places=0,
        max_digits=20, null=True
    )
    plan_id = models.CharField(
        _("Plan ID"),
        max_length=50,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.domain.name}.{self.domain.extension} - {self.nickname} month plan"


@disable_for_loaddata
def recurring_domain_create(sender, instance, *args, **kwargs):
    if not instance.plan_id:
        recurring = stripe.Price.create(
            unit_amount=int(instance.unit_amount * 100),
            nickname=instance.nickname,
            currency="usd",
            recurring={"interval": "month"},
            product=instance.domain.stripe_recurring_id,
        )

        instance.plan_id = recurring.id

    elif instance.plan_id:
        stripe.Price.modify(
            instance.plan_id,
            nickname=instance.nickname,
        )


pre_save.connect(recurring_domain_create, sender=Plan)


class Domain(models.Model):
    RATING = (
        ('bad', 'bad'),
        ('poor', 'poor'),
        ('fair', 'fair'),
        ('good', 'good'),
        ('excellent', 'excellent'),
    )
    STATUS = (
        ('available', 'AVAILABLE'),
        ('sold', 'SOLD')
    )
    ACTIVE_STATUS = (
        ('waiting', 'WAITING'),
        ('pending', 'PENDING'),
        ('listed', 'LISTED'),
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="domains"
    )
    name = models.CharField(_("Domain name"), max_length=200)
    length = models.PositiveIntegerField(
        _("Domain length"),
        blank=True, null=True
    )
    is_active = models.CharField(
        choices=ACTIVE_STATUS,
        default='waiting',
        max_length=10
    )
    extension = models.CharField(
        _("Domain extension"),
        max_length=150, null=True
    )
    stripe_recurring_id = models.CharField(
        _("Recurring product id"),
        max_length=150,
        null=True, blank=True
    )
    stripe_one_time_id = models.CharField(
        _("One time product id"),
        max_length=150,
        null=True, blank=True
    )
    price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    discount_price = models.DecimalField(
        _("Discount Price"),
        decimal_places=0,
        max_digits=20, null=True, blank=True
    )
    negotiable_price = models.DecimalField(
        _("Negotiable Domain price"),
        decimal_places=0,
        max_digits=20, null=True, blank=True
    )
    favorite_count = models.IntegerField(
        _("Favorite Count"),
        null=True,
        default=0,
        blank=True
    )
    featured = models.BooleanField(
        _("Featured"),
        default=False
    )
    domain_length = models.CharField(
        _("Domain length rating"),
        choices=RATING,
        blank=True,
        max_length=150
    )
    status = models.CharField(
        max_length=25,
        default='available',
        choices=STATUS,
        verbose_name=_("Status of the domain")
    )
    pronouncement = models.CharField(
        _("Domain pronouncement rating"),
        choices=RATING,
        default='available',
        blank=True,
        max_length=150
    )
    brandable = models.CharField(
        _("Domain brandable rating"),
        choices=RATING,
        blank=True, max_length=150
    )
    thumbnail_image = models.ImageField(
        _("Thumbnail image"),
        upload_to='domains/%Y/%m/%d/',
        null=True, blank=True
    )
    mockup_1 = models.FileField(
        _("Mockup 1"),
        upload_to='mockups/%Y/%m/%d/',
        null=True, blank=True
    )
    syllable = models.PositiveIntegerField(
        verbose_name=_("Syllable count"),
        null=True,
        blank=True
    )
    mockup_2 = models.FileField(
        _("Mockup 2"),
        upload_to='mockups/%Y/%m/%d/',
        null=True, blank=True
    )
    mockup_3 = models.FileField(
        _("Mockup 3"),
        upload_to='mockups/%Y/%m/%d/',
        null=True, blank=True
    )
    slug = models.SlugField(
        _("Domain slug"),
        null=True,
        unique=True,
        blank=True,
        default=None,
        max_length=250
    )
    date_updated = models.DateTimeField(auto_now=True, null=True)
    tags = models.ManyToManyField(
        Tag,
        verbose_name=_("Tags"),
        related_name="domains",
        blank=True
    )
    date_created = models.DateTimeField(
        _("Date Published"),
        default=timezone.now
    )
    industry = models.ManyToManyField(
        Industry,
        verbose_name=_("Industries"),
        related_name="industry",
        blank=True
    )
    visit_count = models.PositiveIntegerField(_("Visitor Count"), default=0)
    stripe_product_id = models.CharField(blank=True, null=True, max_length=120)
    featured_plan_id = models.CharField(blank=True, null=True, max_length=120)

    @property
    def ranking(self):
        return self.visit_count

    @property
    def get_related(self):
        tags = self.tags.all()
        industries = self.industry.all()
        queryset = Domain.objects.filter(
            tags__in=tags,
            industry__in=industries
        ).exclude(id=self.pk).distinct()
        return queryset

    def get_absolute_url(self):
        return reverse('main:domain-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.length = len(self.name)

        # Estimated syllable count from `syllables` package
        self.syllable = syllables.estimate(self.name)

        if self.thumbnail_image:
            self.thumbnail_image = compress_image(
                img=self.thumbnail_image,
                instance=self.__str__()
            )
        if self.mockup_1:
            self.mockup_1 = compress_image(
                img=self.mockup_1,
                instance=self.__str__()
            )
        if self.mockup_2:
            self.mockup_2 = compress_image(
                img=self.mockup_2,
                instance=self.__str__()
            )
        if self.mockup_3:
            self.mockup_3 = compress_image(
                img=self.mockup_3,
                instance=self.__str__()
            )
        if not self.owner:
            self.owner = User.objects.filter(is_superuser=True).first()
        if not self.slug:
            slug = slugify(f'{self.name}-{self.extension}')
            duplicate = Domain.objects.filter(slug=slug)
            if duplicate:
                slug = f"{slug}-1"
            self.slug = slug
        if not self.length:
            self.length = len(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}.{self.extension}'

    def get_absolute_url(self):
        return reverse('main:domain-detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Domain"
        verbose_name_plural = "Domains"


def update_stripe_details(instance, images, image, price):
    # TODO : Fix this function. It`s not appropriate solution and messy
    i = instance
    if not i.stripe_one_time_id and not i.stripe_recurring_id and not i.stripe_product_id:

        new_domain = stripe.Product.create(
            name=i.name,
            type="good",
            images=images,
            attributes=["name"]
        )
        sku = stripe.SKU.create(
            attributes={

marketplace/models.py
from django.db import models
from django.utils.translation import ugettext as _


class EstimatedDomainPrice(models.Model):
    domain = models.CharField(max_length=50)
    price = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Estimated Domain Price"
        verbose_name_plural = "Estimated Domain Prices"

    def __str__(self):
        return f'{self.domain} - {self.price}'


class BrainstormingKeywords(models.Model):
    key = models.CharField(_("Main Key"), max_length=50)
    industry = models.ManyToManyField("main.Industry", blank=True)
    count = models.PositiveIntegerField(_("Count"), default=1)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)

    class Meta:
        verbose_name = "Brainstorming Key"
        verbose_name_plural = "Brainstorming Keys"

    @property
    def industries(self):
        return ", ".join(item.name for item in self.industry.all())

    def __str__(self):
        return self.key


class DomainNegotiation(models.Model):
    domain = models.ForeignKey("main.Domain", on_delete=models.CASCADE )
    email = models.CharField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=40, null=True, blank=True)
    price = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Domain Negotiation"
        verbose_name_plural = "Domain Negotiations"

    def __str__(self):
        return f"{self.domain} deal from {self.email}"

marketplace/forms.py
from decimal import Decimal

from django import forms

from main.models import Domain, Industry


class DomainCreateForm(forms.ModelForm):
    price = forms.DecimalField()
    negotiable_price = forms.DecimalField(
        label="Lowest price",
        required=False,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Minimum price for the domain. (Optional)'
    }))
    
    class Meta:
        model = Domain
        fields = [
            'name', 'extension', 'price',
            'negotiable_price', 'thumbnail_image',
            'owner'
        ]
    
    def __init__(self, *args, **kwargs):
        # important to "pop" added kwarg before call to parent's constructor
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)
    
    def clean_owner(self):
        return self.request.user

templates/marketplace/domain/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>Brandpulsar | Add Domain</title>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

<title>Password update: {{request.user.email}} | Brandpulsar</title>


{% endblock meta %}

{% block content %}

<style>
    .select2.select2-container .select2-selection--multiple .select2-search--inline .select2-search__field {
        width: 100% !important;
        height: calc(2.25rem + 2px);
    }

    .select2-container--default .select2-selection--multiple,
    .select2-container--default.select2-container--open.select2-container--above .select2-selection--single,
    .select2-container--default.select2-container--open.select2-container--above .select2-selection--multiple,
    .select2-container--default.select2-container--focus .select2-selection--multiple {
        border: none;
    }
</style>

<section class="profile-header-section">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h1 class="text-white">Add your domain</h1>
                <p class="text-white">Brand Pulsar is a marketplace to sell premium domain names that is built around
                    the ideas and spirit of its community.
                </p>
            </div>
            <div class="col-md-7"></div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h3>Benefits of adding domain</h3>
                <p class="mb-3">With hundreds of potential buyers visiting our platform every day, your domain can get
                    sold only
                    within a few days.
                </p>
                <p>Wanna sell fast? <span class="purple">Feature</span> your domain to get more exposure. Be on top of
                    the lists and appear on
                    banners.
                </p>
            </div>
            <div class="col-md-7">
                <div class="domain-form-box">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="row">
                            <div class="input-box col">
                                <input type="text" name="name" maxlength="200" id="id_name" required />
                                <label for="id_name">Domain name</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-box col">
                                <select name="extension" id="id_extension">
                                    <option value="com">com</option>
                                    <option value="net">net</option>
                                    <option value="org">org</option>
                                    <option value="co">co</option>
                                    <option value="io">io</option>
                                </select>
                                <label for="id_extension">Domain extension</label>
                            </div>
                        </div>
                        <div id="estimated-price"></div>
                        <div class="row">
                            <div class="input-box col">
                                <input type="number" name="price" required id="id_price" />
                                <label for="id_price">Domain price</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-box col">
                                <select name="negotiation" id="id_negotiation">
                                    <option>Choose</option>
                                    <option value="yes">yes</option>
                                    <option value="no">no</option>
                                </select>
                                <label for="id_negotiation">Are you open for negotiations?</label>
                            </div>
                        </div>

                        <div class="row" id="lowest_price_field">
                            <div class="input-box col">
                                <input type="number" name="negotiable_price" id="id_negotiable_price" />
                                <label for="id_negotiable_price">Lowest price ( minimum price for domain )</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-box col">
                                <input type="file" name="thumbnail_image" accept="image/*" id="id_thumbnail_image">
                                <label for="id_thumbnail_image">Thumbnail image:</label>
                            </div>
                        </div>
                        <p class="d-flex mb-2" style="color: #0C1142;font-size: 10px;line-height: 18px">
                            <input type="checkbox" style="width: auto;margin-right: 5px;margin-top: 5px;" />By checking
                            this box, I agree
                            that
                            brandpulsar.com may
                            contact me from time to time at the email address above to tell me about its
                            services.
                        </p>
                        <input type="submit" class="btn-green btn-md" value="Apply" />
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{% block extra_js %}
<!-- <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script> -->
<script src="{% static 'js/appraisal.js' %}"></script>


{% endblock %}

templates/marketplace/domain/delete.html
{% extends 'base.html' %}
{% block meta %}
<title>Brandpulsar | Delete Domain</title>
{% endblock meta %}

{% block content %}
{% load static %}
<style>
    .header-nav,
    .footer {
        display: none;
    }
</style>
<section class="auth-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="auth-container"
                    style="display: flex;align-items: center;flex-direction: column;justify-content: center;">
                    <h1 class="text-center pb-3">Delete Domain</h1>
                    <h4 class="mb-5">{{ domain }}</h4>
                    <form method="POST">
                        {% csrf_token %}
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        {{form.as_p}}
                        <div class="form-group">
                            <button class="btn-green btn-md" type="submit">Delete</button>
                            <a class="btn-white btn-md" href="{% url 'users:dashboard' %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/marketplace/domain/update.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Brandpulsar | Domain update: {{request.user.email}}</title>
{% endblock meta %}
{% block content %}
<style>
    .header-nav,
    .footer {
        display: none;
    }
</style>
<section class="auth-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="auth-container">
                    <div class="auth-content form-box" style="overflow-y: scroll;width: 100%;">
                        <h1 class="text-center pb-3">Update your domain</h1>

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{field}}{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endif %}
                            <div class="row">
                                <div class="input-box col">
                                    <input type="text" name="name" maxlength="150" id="id_name">
                                    <label for="id_name">Domain name: {{domain.name}}</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="number" name="length" min="0" id="id_length">
                                    <label for="id_length">Domain length: {{domain.length}}</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="text" name="extension" maxlength="150" id="id_extension">
                                    <label for="id_extension">Domain extension: {{domain.extension}}</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="number" name="price" step="1" id="id_price">
                                    <label for="id_price">Domain price: $ {{domain.price}}</label>
                                </div>
                                {% if domain.negotiable_price %}
                                <div class="input-box col">
                                    <input type="number" name="negotiable_price" id="id_negotiable_price" />
                                    <label for="id_negotiable_price">Lowest price ( minimum price for domain )</label>
                                </div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="file" name="thumbnail_image" accept="image/*" id="id_thumbnail_image">
                                    <label for="id_thumbnail_image">Thumbnail image:</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <a href="{% url 'users:dashboard' %}" class="btn-white btn-md">Cancel</a>
                                <button class="btn-green btn-md" type="submit">Update domain</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}