api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'domains/',
        views.DomainListView.as_view(),
        name="domain-list-api"),
    path(
        'my-domains/',
        views.UsersDomainsListView.as_view(),
        name="my-domain-list-api"),
    path(
        'brainstorming/',
        views.DomainBrainStormingAPIView.as_view(),
        name="brainstorming-api"
    ),
    path(
        'domains/<int:pk>/',
        views.SingleDomainAPIView.as_view(),
        name="single-domain-api"),
    path(
        'autocomplete/',
        views.SearchAutoCompleteView.as_view(),
        name="autocomplete-api"),
    path(
        'favourite/',
        views.FavouriteAPIView.as_view(),
        name="favourite-api"),
    path(
        'contacts/',
        views.ContactsAPIView.as_view(),
        name="contact-api"),
    path(
        'negotiate/',
        views.NegotiateContactAPIView.as_view(),
        name="negotiate-api"),
    path(
        'appraisal/',
        views.DomainAppraisalAPIView.as_view(),
        name="domain-appraisal"),
    path(
        'verify/',
        views.VerifyDomainAPIView.as_view(),
        name="verify-domain-redirect"
    ),
]

brandpulsar/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('v1/api/', include('rest_framework.urls')),
    path('v1/api/', include('api.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from main import views
from main.views import *
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import DomainSitemap, StaticViewSitemap, BlogPostSitemap, BlogCategorySitemap

sitemaps = {
    'portfolio': DomainSitemap,
    'blog': BlogPostSitemap,
    'blog-category': BlogCategorySitemap,
    'static': StaticViewSitemap
}

app_name = 'main'

urlpatterns = [
    # Static Pages
    path('', IndexView.as_view(), name='index'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('faq/', Faq.as_view(), name='faq'),
    path('how-it-works/', HowItWorks.as_view(), name='how-it-works'),
    path('knowledge-base/', KnowledgeBase.as_view(), name='knowledge-base'),
    path('terms-of-use/', TermsOfUse.as_view(), name='terms-of-use'),
    path('terms-of-service/', TermsOfService.as_view(), name='terms-of-service'),
    path('privacy-policy/', PrivacyPolicy.as_view(), name='privacy-policy'),
    # On Pages
    path('how-to-name-your-brand/', HowToNameYourBrand.as_view(), name='how-to-name-your-brand'),
    path('what-makes-a-name-brandable/', WhatMakesaNameBrandable.as_view(), name='what-makes-a-name-brandable'),
    # Helper Pages
    path('success/', Success.as_view(), name='success'),
    path('thank-you/', ThankYou.as_view(), name='thank-you'),
    path('cancel/', Canceled.as_view(), name='cancel'),
    path('create-session/', Session.as_view(), name='create-session'),
    path('create-checkout-session/', create_checkout_session, name='create-checkout-session'),
    path('create-customer-portal-session/', create_customer_portal_session, name='create-customer-portal-session'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('ajax-favorite', ajax_favorite_view, name='ajax_favorite_view'),
    path('mark-as-featured/', mark_as_featured, name='mark-as-featured'),
    # Business Names
    path('startup-names/', StartupNames.as_view(), name='startup-names'),
    path('website-names/', WebsiteNames.as_view(), name='website-names'),
    path('domain-names/', DomainNames.as_view(), name='domain-names'),
    path('company-names/', CompanyNames.as_view(), name='company-names'),
    # Blog
    path('blog/<slug:slug>/', SingleBlogPostView.as_view(), name='blog-post'),
    path('blog/categories/<slug:slug>/',
         SingleBlogCategoryView.as_view(), name='blog-category'),
    # Customers 
    path('customers/', Customers.as_view(), name='customers'),
    path('customers/<slug:slug>/', SingleCustomer.as_view(), name='single-customer'),
    # Domains
    path('domains/', DomainList.as_view(), name='domains'),
    path('domains/industries/<slug:slug>/',
         SingleIndustryView.as_view(), name='industry-detail'),
    path('domains/<slug:slug>/', SingleDomainView.as_view(), name='domain-detail'),
    path('industries/', IndustryListView.as_view(), name='industries'),
    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', RobotsTXT.as_view(), name='robots.txt'),
    # Webhooks
    path('instalment-hooks/', instalment_webhook_view, name='instalment-hooks'),
    path('featured-hooks/', featured_webhook_view, name='featured-hooks'),
]

handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

marketplace/urls.py
from django.urls import path
from . import views

app_name='marketplace'

urlpatterns = [
    path('become-a-seller/', views.BecomeASellerView.as_view(), name='become-a-seller'),
    path('create/', views.DomainCreateView.as_view(), name='create-domain'),
    path('setup/<int:pk>/', views.DomainSetupView.as_view(), name='setup-domain'),
    path('update/<int:pk>/', views.DomainUpdateView.as_view(), name='update-domain'),
    path('delete/<int:pk>/', views.DomainDeleteView.as_view(), name='delete-domain'),
    path('brainstorming/', views.BrainStormingView.as_view(), name="brainstorming-view"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register-view"),
    path('activate/', views.ActivateView.as_view(), name="register-done-view"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('activate/<uidb64>/<token>/',
         views.ActivateView.as_view(),
         name="activate-view"),
    path('login/', views.LoginView.as_view(), name="login-view"),
    path('logout/', views.LogOutView.as_view(), name="logout-view"),
    path(
        'password/reset/',
        views.CustomPasswordResetView.as_view(),
        name="password-reset"),
    path(
        'password/confirm/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path(
        'password/done/',
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_complete"),
    path('edit/',
         login_required(views.UserEditView.as_view()),
         name="user-edit-view"),
    path('edit/password/',
         login_required(views.UserPasswordEditView.as_view()),
         name="user-edit-password-view"),
    # path(
    #     'payment-methods/',
    #     views.PaymentMethodListView.as_view(),
    #     name="payment-method-list"
    # ),
    # path(
    #    'add/payment-method/',
    #    views.PaymentMethodCreateView.as_view(),
    #    name="add-payment-method"
    # ),
    # path(
    #    'update/payment-method/<int:pk>/',
    #    views.PaymentMethodUpdateView.as_view(),
    #    name="update-payment-method"
    # ),
    # path(
    #    'delete/payment-method/<int:pk>/',
    #    views.PaymentMethodDeleteView.as_view(),
    #    name="delete-payment-method",
    # ),
    # path('payment-history/', views.PaymentHistoryView.as_view(),
    #      name="payment-history",)
]

templates/partials/_footer.html
{% load static %}
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="footer-top">
          <img src="{% static 'images/brandpulsar-3.svg' %}" alt="Brandpulsar" />
          <ul class="social">
            <li>
              <a href="https://www.facebook.com/BrandPulsar/">
                <svg xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1"
                  id="Capa_1" x="0px" y="0px" viewBox="0 0 159.822 159.822"
                  style="enable-background:new 0 0 159.822 159.822;" xml:space="preserve" width="512px" height="512px">
                  <g>
                    <g>
                      <path
                        d="M76.715,36.172c4.142,0,7.5-3.358,7.5-7.5C84.215,21.133,90.349,15,97.887,15h21.179c4.142,0,7.5-3.358,7.5-7.5   s-3.358-7.5-7.5-7.5H97.887c-15.81,0-28.672,12.862-28.672,28.672C69.215,32.813,72.573,36.172,76.715,36.172z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M117.458,59.627H40.756c-4.142,0-7.5,3.358-7.5,7.5s3.358,7.5,7.5,7.5h28.46v77.695c0,4.142,3.358,7.5,7.5,7.5   c4.142,0,7.5-3.358,7.5-7.5V74.627h33.243c4.142,0,7.5-3.358,7.5-7.5S121.6,59.627,117.458,59.627z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                    </g>
                  </g>
                </svg>
              </a>
            </li>
            <li>
              <a href="https://twitter.com/BrandPulsar/">
                <svg xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1"
                  id="Capa_1" x="0px" y="0px" viewBox="0 0 198.737 198.737"
                  style="enable-background:new 0 0 198.737 198.737;" xml:space="preserve" width="512px" height="512px"
                  class="">
                  <g>
                    <g>
                      <path
                        d="M197.399,42.479c-2.36-3.401-7.034-4.247-10.438-1.886l-23.288,16.159c-2.115,1.467-3.329,3.916-3.218,6.487   c0.067,1.542,0.1,2.988,0.1,4.42c0,47.603-36.222,96.84-96.839,96.84c-12.357,0-24.497-2.352-35.843-6.889l35.939-10.052   c3.989-1.116,6.318-5.254,5.202-9.243c-1.116-3.988-5.25-6.318-9.243-5.202L5.48,148.299c-2.846,0.796-4.959,3.189-5.397,6.112   c-0.437,2.922,0.882,5.83,3.37,7.425C21.477,173.391,42.316,179.5,63.716,179.5c42.057,0,68.398-19.87,83.091-36.538   c18.27-20.728,28.748-48.174,28.748-75.302c0-0.297-0.001-0.594-0.003-0.892l19.961-13.85   C198.915,50.556,199.76,45.883,197.399,42.479z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M16.555,40.14l75.585,38.315c1.072,0.544,2.234,0.811,3.39,0.811c1.646,0,3.282-0.541,4.629-1.598   c2.293-1.798,3.337-4.761,2.677-7.6c-0.501-2.154-0.754-4.396-0.754-6.662c0-16.083,13.087-29.168,29.173-29.168   c8.041,0,15.804,3.357,21.296,9.211c2.052,2.188,5.211,2.941,8.031,1.917l23.328-8.476c3.893-1.415,5.903-5.717,4.488-9.61   c-1.414-3.894-5.72-5.901-9.61-4.488l-18.983,6.897c-7.929-6.692-18.083-10.452-28.55-10.452c-22.93,0-41.835,17.561-43.972,39.938   L23.337,26.761c-3.695-1.874-8.208-0.396-10.081,3.298C11.383,33.754,12.86,38.267,16.555,40.14z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M12.689,85.053l16.608,4.585c0.668,0.185,1.339,0.272,2,0.272c3.289,0,6.307-2.181,7.225-5.506   c1.103-3.992-1.241-8.123-5.233-9.226l-16.608-4.585c-3.99-1.102-8.123,1.24-9.226,5.233C6.353,79.82,8.696,83.95,12.689,85.053z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M27.25,107.376c-4.139,0.157-7.367,3.639-7.21,7.778c0.153,4.043,3.478,7.216,7.49,7.216c0.096,0,0.192-0.002,0.288-0.005   l16.562-0.628c4.139-0.157,7.367-3.639,7.211-7.779c-0.157-4.139-3.648-7.363-7.778-7.21L27.25,107.376z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                    </g>
                  </g>
                </svg>
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/BrandPulsar/">
                <svg xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1"
                  id="Layer_1" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 169.063 169.063"
                  style="enable-background:new 0 0 169.063 169.063;" xml:space="preserve" class="">
                  <g>
                    <g>
                      <path
                        d="M122.406,0H46.654C20.929,0,0,20.93,0,46.655v75.752c0,25.726,20.929,46.655,46.654,46.655h75.752   c25.727,0,46.656-20.93,46.656-46.655V46.655C169.063,20.93,148.133,0,122.406,0z M154.063,122.407   c0,17.455-14.201,31.655-31.656,31.655H46.654C29.2,154.063,15,139.862,15,122.407V46.655C15,29.201,29.2,15,46.654,15h75.752   c17.455,0,31.656,14.201,31.656,31.655V122.407z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M84.531,40.97c-24.021,0-43.563,19.542-43.563,43.563c0,24.02,19.542,43.561,43.563,43.561s43.563-19.541,43.563-43.561   C128.094,60.512,108.552,40.97,84.531,40.97z M84.531,113.093c-15.749,0-28.563-12.812-28.563-28.561   c0-15.75,12.813-28.563,28.563-28.563s28.563,12.813,28.563,28.563C113.094,100.281,100.28,113.093,84.531,113.093z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                      <path
                        d="M129.921,28.251c-2.89,0-5.729,1.17-7.77,3.22c-2.051,2.04-3.23,4.88-3.23,7.78c0,2.891,1.18,5.73,3.23,7.78   c2.04,2.04,4.88,3.22,7.77,3.22c2.9,0,5.73-1.18,7.78-3.22c2.05-2.05,3.22-4.89,3.22-7.78c0-2.9-1.17-5.74-3.22-7.78   C135.661,29.421,132.821,28.251,129.921,28.251z"
                        data-original="#000000" class="active-path" data-old_color="#000000" fill="#605f71" />
                    </g>
                  </g>
                </svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row pb-4">
      <div class="col-xs-12">
        <div class="footer-nav">
          <div class="footer-nav-item">
            <h4>Company</h4>
            <ul class="menu-list">
              <li><a href="{% url 'main:domains' %}">Domains</a></li>
              <li><a href="{% url 'main:industries' %}">Industries</a></li>
              <li><a href="{% url 'users:login-view' %}">Log in</a></li>
              <li><a href="{% url 'users:register-view' %}">Sign up</a></li>
              <li><a href="{% url 'main:customers' %}">Customers</a></li>
              <li><a href="{% url 'main:contact' %}">Contact us</a></li>
            </ul>
          </div>
          <div class="footer-nav-item">
            <h4>Knowledge Base</h4>
            <ul class="menu-list">
              <li><a href="{% url 'main:blog' %}">Blog</a></li>
              <li><a href="{% url 'main:how-it-works' %}">How it works</a></li>
              <li><a href="{% url 'main:faq' %}">FAQ</a></li>
              {% if request.user.is_authenticated %}
              {% else %}
              <li><a href="{% url 'marketplace:become-a-seller' %}">Become a seller</a></li>
              {% endif %}
              <li><a href="{% url 'main:how-to-name-your-brand' %}">How to name your brand</a></li>
              <li><a href="{% url 'main:what-makes-a-name-brandable' %}">What makes a name brandable</a></li>
            </ul>
          </div>
          <div class="footer-nav-item">
            <h4>Name ideas</h4>
            <ul class="menu-list">
              <li>
                <a href="{% url 'main:website-names' %}">Website names</a>
              </li>
              <li>
                <a href="{% url 'main:startup-names' %}">Startup names</a>
              </li>
              <li>
                <a href="{% url 'main:domain-names' %}">Domain names</a>
              </li>
              <li>
                <a href="{% url 'main:company-names' %}">Company names</a>
              </li>
            </ul>
          </div>
          <div class="footer-nav-item footer-nav-item-content">
            <p class="mb-4">
              Brandpulsar is the go-to option for many existing businesses or start-ups looking for premium but
              affordable domain
              names. Our domains come with premade logos and design mockups so brands can be immediately launched.
            </p>
            <ul class="contact-details">
              <li><a href="mailto:sales@brandpulsar.com">sales@brandpulsar.com</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="line mb-5" style="background-color: #605f712e;"></div>
        <h4>Industries</h4>
        <ul class="menu-list industry-list" style="display: flex;flex-direction: column;flex-wrap: wrap;height: 500px;">
          {% for industry in footer_industries %}
          <li><a href="{% url 'main:industry-detail' industry.slug %}">{{ industry.name }}</a></li>
          {% endfor %}

        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="line mb-5" style="background-color: #605f712e;"></div>
      </div>
    </div>
    <div class="row pb-4">
      <div class="col-sm-12">
        <div class="legal">
          <p>Copyright © Brandpulsar - All rights reserved</p>
          <img src="{% static 'images/payment-methods.svg' %}" />
          <ul>
            <li><a href="{% url 'main:privacy-policy' %}">Privacy policy</a></li>
            <li><a href="{% url 'main:terms-of-use' %}">Terms of use</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/_header.html
{% load static %}
<header class="header-nav">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 p-0">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="{% url 'main:index' %}">
            <img class="cosmic-logo" src="{% static 'images/brandpulsar-3.svg' %}" alt="Brandpulsar" />
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
              <svg version="1.1" id="Layer_1" xmlns="https://www.w3.org/2000/svg"
                xmlns:xlink="https://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30"
                style="enable-background:new 0 0 30 30;" xml:space="preserve">
                <style type="text/css">
                  .st0 {
                    fill-rule: evenodd;
                    clip-rule: evenodd;
                    fill: #FFFFFF;
                  }
                </style>
                <desc>Created with Sketch.</desc>
                <g id="Page-1">
                  <g id="Mobile" transform="translate(-330.000000, -15.000000)">
                    <g id="Header" transform="translate(-2.000000, 0.000000)">
                      <g id="Menu" transform="translate(332.000000, 15.000000)">
                        <g id="Hambargar">
                          <rect id="Rectangle-2" class="st0" width="20" height="4" />
                          <rect id="Rectangle-2-Copy" y="13" class="st0" width="30" height="4" />
                          <polygon id="Rectangle-2-Copy-2" class="st0" points="0,26 20,26 20,30 0,30 					" />
                        </g>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:domains' %}">Domains</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:industries' %}">Industries</a>
              </li>


              <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:brainstorming-view' %}">Brainstorming Tool</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  Resources
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'main:how-it-works' %}">How it works</a>
                  <a class="dropdown-item" href="{% url 'main:customers' %}">Customers</a>
                  <a class="dropdown-item" href="{% url 'main:faq' %}">FAQ</a>
                  <a class="dropdown-item" href="{% url 'main:blog' %}">Blog</a>
                  <a class="dropdown-item" href="{% url 'main:how-to-name-your-brand' %}">How to name your brand</a>
                  <a class="dropdown-item" href="{% url 'main:what-makes-a-name-brandable' %}">What Makes a Name
                    Brandable</a>
                </div>
              </li>
            </ul>
            <ul class="navbar-nav mobile-hide ml-auto">
              <li id="login-nav-item" class="nav-item">
                {% if request.user.is_authenticated %}
                <div class="dropdown">
                  <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.profile_picture %}
                    <img class="login-icon" src="{{request.user.profile_picture.url}}" alt="">
                    {% else %}
                    <img class="login-icon" src="{% static 'images/avatar-default.svg' %}" alt="">
                    {% endif %}
                    {{ request.user.name }} {{ request.user.surname }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left" aria-labelledby="dropdownMenu2">
                    <a href="{% url 'users:dashboard' %}" class="dropdown-item" type="button">Dashboard</a>
                    <a href="{% url 'users:user-edit-view' %}" class="dropdown-item" type="button">Account</a>
                    <a href="{% url 'main:favorites' %}" class="dropdown-item" type="button">Favorites</a>
                    <a href="{% url 'marketplace:create-domain' %}" class="dropdown-item" type="button">Add a domain</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'users:logout-view' %}" class="dropdown-item" type="button">Log out</a>
                  </div>
                </div>
                {% else %}
              <li class="nav-item mr-2 dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  Login
                </a>
                <div class="dropdown-menu auth-actions-container" aria-labelledby="navbarDropdown">
                  <div class="auth-actions">
                    <a href="{% url 'users:login-view' %}" class="btn-green btn-md">Log in</a>
                    or
                    <a href="{% url 'users:register-view' %}" class="btn-white btn-md btn-arrow"><span>Sign up</span>
                      <img src="{% static 'images/next-btn-dark.svg' %}" /></a>
                  </div>
                </div>
              </li>
              <li class="nav-item ml-2 mr-3">
                <a class="btn-green btn-md" style="color: #010529;"
                  href="{% url 'marketplace:become-a-seller' %}">Become a
                  seller</a>
              </li>
              <!-- <li id="fav-nav-item" class="nav-item">
                <a href="{% url 'main:favorites' %}">
                  <div id="fav-count">
                    0
                  </div>

                </a>
              </li> -->
              <li class="nav-item fav-link " id="fav-nav-item">
                <a href="{% url 'main:favorites' %}">
                  <svg xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1"
                    id="Capa_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;"
                    xml:space="preserve" width="512px" height="512px">
                    <g>
                      <g>
                        <g>
                          <path
                            d="M474.644,74.27C449.391,45.616,414.358,29.836,376,29.836c-53.948,0-88.103,32.22-107.255,59.25    c-4.969,7.014-9.196,14.047-12.745,20.665c-3.549-6.618-7.775-13.651-12.745-20.665c-19.152-27.03-53.307-59.25-107.255-59.25    c-38.358,0-73.391,15.781-98.645,44.435C13.267,101.605,0,138.213,0,177.351c0,42.603,16.633,82.228,52.345,124.7    c31.917,37.96,77.834,77.088,131.005,122.397c19.813,16.884,40.302,34.344,62.115,53.429l0.655,0.574    c2.828,2.476,6.354,3.713,9.88,3.713s7.052-1.238,9.88-3.713l0.655-0.574c21.813-19.085,42.302-36.544,62.118-53.431    c53.168-45.306,99.085-84.434,131.002-122.395C495.367,259.578,512,219.954,512,177.351    C512,138.213,498.733,101.605,474.644,74.27z M309.193,401.614c-17.08,14.554-34.658,29.533-53.193,45.646    c-18.534-16.111-36.113-31.091-53.196-45.648C98.745,312.939,30,254.358,30,177.351c0-31.83,10.605-61.394,29.862-83.245    C79.34,72.007,106.379,59.836,136,59.836c41.129,0,67.716,25.338,82.776,46.594c13.509,19.064,20.558,38.282,22.962,45.659    c2.011,6.175,7.768,10.354,14.262,10.354c6.494,0,12.251-4.179,14.262-10.354c2.404-7.377,9.453-26.595,22.962-45.66    c15.06-21.255,41.647-46.593,82.776-46.593c29.621,0,56.66,12.171,76.137,34.27C471.395,115.957,482,145.521,482,177.351    C482,254.358,413.255,312.939,309.193,401.614z"
                            data-original="#000000" class="active-path" data-old_color="#000000" fill="#ffffff" />
                        </g>
                      </g>
                    </g>
                  </svg>
                </a>
              </li>
              {% endif %}
              </li>



            </ul>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

templates/partials/_sidebar.html
{% load static %}
<div class="sidebar bg-grey">
    <h4 class="mb-3">Filters</h4>
    <div class="mb-5 line"></div>
    <h6>Industries</h6>
    <ul class="induestries">
        {% for industry in industries %}
            {% if industry.name != 'Uncategorized' %}
                <li><a href="{% url 'main:industry-detail' industry.slug %}">{{ industry.name }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
    <form action="" method="get" class="filter-form">
        {{ filter.form }}
        <input type="submit" value="Filter" class="filter-btn"/>
    </form>
</div>