api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'domains/',
        views.DomainListView.as_view(),
        name="domain-list-api"),
    path(
        'my-domains/',
        views.UsersDomainsListView.as_view(),
        name="my-domain-list-api"),
    path(
        'brainstorming/',
        views.DomainBrainStormingAPIView.as_view(),
        name="brainstorming-api"
    ),
    path(
        'domains/<int:pk>/',
        views.SingleDomainAPIView.as_view(),
        name="single-domain-api"),
    path(
        'autocomplete/',
        views.SearchAutoCompleteView.as_view(),
        name="autocomplete-api"),
    path(
        'favourite/',
        views.FavouriteAPIView.as_view(),
        name="favourite-api"),
    path(
        'contacts/',
        views.ContactsAPIView.as_view(),
        name="contact-api"),
    path(
        'negotiate/',
        views.NegotiateContactAPIView.as_view(),
        name="negotiate-api"),
    path(
        'appraisal/',
        views.DomainAppraisalAPIView.as_view(),
        name="domain-appraisal"),
    path(
        'verify/',
        views.VerifyDomainAPIView.as_view(),
        name="verify-domain-redirect"
    ),
]

brandpulsar/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('v1/api/', include('rest_framework.urls')),
    path('v1/api/', include('api.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from main import views
from main.views import *
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import DomainSitemap, StaticViewSitemap, BlogPostSitemap, BlogCategorySitemap

sitemaps = {
    'portfolio': DomainSitemap,
    'blog': BlogPostSitemap,
    'blog-category': BlogCategorySitemap,
    'static': StaticViewSitemap
}

app_name = 'main'

urlpatterns = [
    # Static Pages
    path('', IndexView.as_view(), name='index'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('faq/', Faq.as_view(), name='faq'),
    path('how-it-works/', HowItWorks.as_view(), name='how-it-works'),
    path('knowledge-base/', KnowledgeBase.as_view(), name='knowledge-base'),
    path('terms-of-use/', TermsOfUse.as_view(), name='terms-of-use'),
    path('terms-of-service/', TermsOfService.as_view(), name='terms-of-service'),
    path('privacy-policy/', PrivacyPolicy.as_view(), name='privacy-policy'),
    # On Pages
    path('how-to-name-your-brand/', HowToNameYourBrand.as_view(), name='how-to-name-your-brand'),
    path('what-makes-a-name-brandable/', WhatMakesaNameBrandable.as_view(), name='what-makes-a-name-brandable'),
    # Helper Pages
    path('success/', Success.as_view(), name='success'),
    path('thank-you/', ThankYou.as_view(), name='thank-you'),
    path('cancel/', Canceled.as_view(), name='cancel'),
    path('create-session/', Session.as_view(), name='create-session'),
    path('create-checkout-session/', create_checkout_session, name='create-checkout-session'),
    path('create-customer-portal-session/', create_customer_portal_session, name='create-customer-portal-session'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('ajax-favorite', ajax_favorite_view, name='ajax_favorite_view'),
    path('mark-as-featured/', mark_as_featured, name='mark-as-featured'),
    # Business Names
    path('startup-names/', StartupNames.as_view(), name='startup-names'),
    path('website-names/', WebsiteNames.as_view(), name='website-names'),
    path('domain-names/', DomainNames.as_view(), name='domain-names'),
    path('company-names/', CompanyNames.as_view(), name='company-names'),
    # Blog
    path('blog/<slug:slug>/', SingleBlogPostView.as_view(), name='blog-post'),
    path('blog/categories/<slug:slug>/',
         SingleBlogCategoryView.as_view(), name='blog-category'),
    # Customers 
    path('customers/', Customers.as_view(), name='customers'),
    path('customers/<slug:slug>/', SingleCustomer.as_view(), name='single-customer'),
    # Domains
    path('domains/', DomainList.as_view(), name='domains'),
    path('domains/industries/<slug:slug>/',
         SingleIndustryView.as_view(), name='industry-detail'),
    path('domains/<slug:slug>/', SingleDomainView.as_view(), name='domain-detail'),
    path('industries/', IndustryListView.as_view(), name='industries'),
    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', RobotsTXT.as_view(), name='robots.txt'),
    # Webhooks
    path('instalment-hooks/', instalment_webhook_view, name='instalment-hooks'),
    path('featured-hooks/', featured_webhook_view, name='featured-hooks'),
]

handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register-view"),
    path('activate/', views.ActivateView.as_view(), name="register-done-view"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('activate/<uidb64>/<token>/',
         views.ActivateView.as_view(),
         name="activate-view"),
    path('login/', views.LoginView.as_view(), name="login-view"),
    path('logout/', views.LogOutView.as_view(), name="logout-view"),
    path(
        'password/reset/',
        views.CustomPasswordResetView.as_view(),
        name="password-reset"),
    path(
        'password/confirm/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path(
        'password/done/',
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_complete"),
    path('edit/',
         login_required(views.UserEditView.as_view()),
         name="user-edit-view"),
    path('edit/password/',
         login_required(views.UserPasswordEditView.as_view()),
         name="user-edit-password-view"),
    # path(
    #     'payment-methods/',
    #     views.PaymentMethodListView.as_view(),
    #     name="payment-method-list"
    # ),
    # path(
    #    'add/payment-method/',
    #    views.PaymentMethodCreateView.as_view(),
    #    name="add-payment-method"
    # ),
    # path(
    #    'update/payment-method/<int:pk>/',
    #    views.PaymentMethodUpdateView.as_view(),
    #    name="update-payment-method"
    # ),
    # path(
    #    'delete/payment-method/<int:pk>/',
    #    views.PaymentMethodDeleteView.as_view(),
    #    name="delete-payment-method",
    # ),
    # path('payment-history/', views.PaymentHistoryView.as_view(),
    #      name="payment-history",)
]

marketplace/models.py
from django.db import models
from django.utils.translation import ugettext as _


class EstimatedDomainPrice(models.Model):
    domain = models.CharField(max_length=50)
    price = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Estimated Domain Price"
        verbose_name_plural = "Estimated Domain Prices"

    def __str__(self):
        return f'{self.domain} - {self.price}'


class BrainstormingKeywords(models.Model):
    key = models.CharField(_("Main Key"), max_length=50)
    industry = models.ManyToManyField("main.Industry", blank=True)
    count = models.PositiveIntegerField(_("Count"), default=1)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)

    class Meta:
        verbose_name = "Brainstorming Key"
        verbose_name_plural = "Brainstorming Keys"

    @property
    def industries(self):
        return ", ".join(item.name for item in self.industry.all())

    def __str__(self):
        return self.key


class DomainNegotiation(models.Model):
    domain = models.ForeignKey("main.Domain", on_delete=models.CASCADE )
    email = models.CharField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=40, null=True, blank=True)
    price = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Domain Negotiation"
        verbose_name_plural = "Domain Negotiations"

    def __str__(self):
        return f"{self.domain} deal from {self.email}"

users/models/favourites.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model

User = get_user_model()


class Favourites(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="favourites",
        verbose_name = "Customer"
    )
    domains = models.ManyToManyField(
        "main.Domain",
        related_name='favourites',
        verbose_name = "Domain list",
        blank=True
    )

    class Meta:
        verbose_name = "Favourite"
        verbose_name_plural = "Favourites"
    
    def __str__(self):
        return f'{self.user} - favourites'

users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm


User = get_user_model()


class RegisterForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, 
    from the given email and password.
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification."
    )

    class Meta:
        model = User
        fields = ['email', 'name', 'surname', 'phone']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2


class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'email-js',
                'id': 'modal-email',
                'placeholder': 'Enter your email'
            }))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'required-js',
                'id': 'modal-password',
                'placeholder': 'Enter your password'
            }))
    remember_me = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'id': 'modal-remember_me'
            }))

    error_messages = {
        'invalid_login': "*Please enter a correct email and password.\
                        Note that both fields may be case-sensitive.",
    }


class UserEditForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    name = forms.CharField(required=False)
    surname = forms.CharField(required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['email', 'name', 'surname', 'profile_picture']


class PasswordResetForm(forms.ModelForm):
    """ Custom Password Reset Form.
        Request object initialized for checking request.user
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'old_password_mismatch': "Old password value didn`t match",
    }
    old_password = forms.CharField()
    second_password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if check_password(old_password, self.request.user.password):
            return old_password
        else:
            raise forms.ValidationError(
                self.error_messages['old_password_mismatch'],
                code='password_mismatch',
            )

    def clean_second_password(self):
        password = self.cleaned_data.get("password1")
        second_password = self.cleaned_data.get("password2")
        if password and second_password and password != second_password:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return second_password


# class PaymentMethodForm(forms.ModelForm):
#    error_messages = {
#        'card_number_length': _("Card number length must be 16 characters"),
#        'card_number_error': _("Card number is not valid"),
#        'end_date_error': _("End date is not valid"),
#        'ccv_error': _("CCV is not valid"),
#    }
#    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
#    class Meta:
#        model=PaymentMethod
#        exclude=['user']
   
#    def clean_card_number(self):
#        card_number = self.cleaned_data.get('card_number')
#        if len(card_number) != 16:
#            print(f"Card number len {len(card_number)}")
#            raise forms.ValidationError(
#                self.error_messages['card_number_length']
#            )
#        try:
#            bool(int(card_number))
#        except:
#            raise forms.ValidationError(
#                self.error_messages['card_number_error']
#            )
#        return card_number
   
#    def clean_end_date(self):
#        end_date = self.cleaned_data.get('end_date')
#        if end_date < datetime.date.today():
#            raise forms.ValidationError(
#                self.error_messages['end_date_error'],
#                code='end_date_error'
#            )
#        return end_date
   
#    def clean_ccv_number(self):
#        ccv_number = self.cleaned_data.get('ccv_number')
#        if len(str(ccv_number)) != 3:
#            raise forms.ValidationError(
#                self.error_messages['ccv_error'],
#                code='ccv_error'
#            )
#        return ccv_number

templates/pages/activate.html
{% extends 'base.html' %}

{% block meta %}
<title>Activate your account</title>
{% endblock meta %}

{% block content %}
{% load static %}
<section class="success-bg standard-bg">
    <div class="container">
        <div class="row mb-4">
            <div class="col-sm-12">
                <h1 class="white text-center">{{message}}</h1>
                <a class="btn-green btn-md" style="margin: 20px auto;display: table"
                    href="{% url 'users:login-view' %}">Go to
                    login</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/pages/blog.html
{% extends 'base.html' %}
{% block meta %}
<title>{{ title }}</title>
<meta name="description" content="{{ meta_description }}" />
<meta property="og:title" content="{{ og_title }}" />
<meta property="og:type" content="{{ og_type }}" />
<meta property="og:url" content="{{ og_url }}" />
<meta property="og:image" content="{{ og_image }}" />
<meta property="og:description" content="{{ og_description }}" />
<meta property="og:site_name" content="{{ og_site }}" />
<meta name="robots" content="index, follow">
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{ og_title }}">
<meta name="twitter:image" content="{{ og_image }}">
<meta name="twitter:site" content="@Brand_Pulsar" />
<meta name="twitter:creator" content="@Brand_Pulsar" />
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
{% endblock meta %}
{% block content %}
{% load static %}
<section class="section-small">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mb-4">Blog</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                {% for post in posts|slice:":1" %}
                <a href="{% url 'main:blog-post' post.slug %}">
                    <article class="new blog-post">
                        <span>New</span>
                        <div class="post-info">
                            <p class="post-category">{{ post.category.title }}</p>
                            <h2>{{ post.title }}</h2>
                            <p class="post-author">{{ post.author.first_name }} {{ post.author.last_name }} |
                                {{ post.date_created|date:"m.d.Y" }}</p>
                        </div>
                        <div class="post-square"></div>
                        <img src="{{ post.thumbnail_image.url }}" alt="{{ post.title }}" class='post-image' />
                    </article>
                </a>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <ul class="small-blog-list">
                    {% for post in posts|slice:"1:5" %}
                    <li>
                        <a href="{% url 'main:blog-post' post.slug %}">
                            <img src="{{ post.thumbnail_image.url }}" alt="{{ post.title }}" />
                            <div class="small-blog-content">
                                <p class="post-category">{{ post.category.title }}</p>
                                <h5>{{ post.title }}</h5>
                                <p class="post-author">{{ post.author.first_name }} {{ post.author.last_name }} |
                                    {{ post.date_created|date:"m.d.Y" }}</p>
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="section-small bg-grey">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <!-- Swiper -->
                <div class="swiper-container categories-slider">
                    <div class="slider-actions">
                        <h4>Categories</h4>
                        <div class="slider-arrows">
                            <div class="swiper-button-prev"></div>
                            <div class="swiper-button-next"></div>
                        </div>
                    </div>
                    <div class="swiper-wrapper">
                        {% for category in categories %}
                        <div class="swiper-slide category-box">
                            <a href="{% url 'main:blog-category' category.slug %}">
                                <h6>{{ category.title }}</h6>
                                <p>{{ category.description }}</p>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-small">
    <div class="container">
        <div class="row">
            {% for post in posts|slice:"5:" %}
            <div class="col-md-4 mb-5">
                <a href="{% url 'main:blog-post' post.slug %}">
                    <article class="blog-post">
                        <div class="post-info">
                            <p class="post-category">{{ post.category.title }}</p>
                            <h5>{{ post.title }}</h5>
                            <p class="post-author">{{ post.author.first_name }} {{ post.author.last_name }} |
                                {{ post.date_created|date:"m.d.Y" }}</p>
                        </div>
                        <div class="post-square"></div>
                        <img src="{{ post.thumbnail_image.url }}" alt="{{ post.title }}" class='post-image' />
                    </article>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="pagination">
                <span class="step-links">
                    {% if posts.has_previous %}
                    <a href="?page=1">
                        <img src="{% static 'images/first.svg' %}" />
                    </a>
                    <a href="?page={{ posts.previous_page_number }}">
                        <img src="{% static 'images/previous.svg' %}" />
                    </a>
                    {% endif %}

                    <span class="current">
                        {{ posts.number }} of {{ posts.paginator.num_pages }}
                    </span>

                    {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">
                        <img src="{% static 'images/next.svg' %}" />
                    </a>
                    <a href="?page={{ posts.paginator.num_pages }}">
                        <img src="{% static 'images/last.svg' %}" />
                    </a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block extra_js %}
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: 3,
        spaceBetween: 30,
        slidesPerGroup: 3,
        loop: true,
        loopFillGroupWithBlank: true,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        breakpoints: {
            // when window width is >= 320px
            320: {
                slidesPerView: 1,
                slidesPerGroup: 1,
                spaceBetween: 20
            },
            // when window width is >= 480px
            480: {
                slidesPerView: 2,
                spaceBetween: 30
            },
            // when window width is >= 640px
            640: {
                slidesPerView: 3,
                slidesPerGroup: 3,
                spaceBetween: 40
            }
        }
    });
    $(".category-box").each(function () {
        var hue = 'rgb(' + (Math.floor((256 - 199) * Math.random()) + 200) + ',' + (Math.floor((256 - 199) * Math.random()) + 200) + ',' + (Math.floor((256 - 199) * Math.random()) + 200) + ')';
        $(this).css("background-color", hue);
    });
</script>
{% endblock %}

templates/pages/canceled.html
{% extends 'base.html' %}
{% block meta %}
<title>{{ title }}</title>
<meta name="description" content="{{ meta_description }}" />
<meta property="og:title" content="{{ og_title }}" />
<meta property="og:type" content="{{ og_type }}" />
<meta property="og:url" content="{{ og_url }}" />
<meta property="og:image" content="{{ og_image }}" />
<meta property="og:description" content="{{ og_description }}" />
<meta property="og:site_name" content="{{ og_site }}" />
<meta name="robots" content="index, follow">
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@Brand_Pulsar" />
<meta name="twitter:creator" content="@Brand_Pulsar" />
{% endblock meta %}

{% block content %}
{% load static %}

<section class="success-bg standard-bg">
    <div class="container">
        <div class="row mb-4">
            <div class="col-sm-12">
                <h1 class="white title text-center">Canceled</h1>
                <p class="white text-center">If you changed your mind, check out other domains.</p>
                <a class="btn-green btn-md" style="display: table;margin: 20px auto;"
                    href="{% url 'main:domains' %}">Check
                    out other
                    domains</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% block meta %}
<title>Brandpulsar | Contact Us</title>
<meta name="description"
    content="Get in touch with us now! You can either call us directly or send us a message and we will reach out to you to discuss your domain goals." />
<meta property="og:title" content="Brandpulsar | Contact Us" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://brandpulsar.com/contact/" />
<meta property="og:image" content="https://brandpulsar.com/static/images/brandpulsar-og.png" />
<meta property="og:description"
    content="Get in touch with us now! You can either call us directly or send us a message and we will reach out to you to discuss your domain goals." />
<meta property="og:site_name" content="Brandpulsar" />
<meta name="robots" content="index, follow">
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{ og_title }}">
<meta name="twitter:image" content="{{ og_image }}">
<meta name="twitter:site" content="@Brand_Pulsar" />
<meta name="twitter:creator" content="@Brand_Pulsar" />
{% endblock meta %}
{% block content %}
{% load static %}

<section class="section contact-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1 class="text-white mb-5">Get in touch</h1>
                <div class="form-box">
                    <h5>We’re happy to answer your questions and respond to your requests or business proposals</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-box col">
                                <input type="text" name="first_name" id="id_first_name" required />
                                <label for="id_first_name">First name</label>
                            </div>
                            <div class="input-box col">
                                <input type="text" name="last_name" id="id_last_name" required />
                                <label for="id_last_name">Last name</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-box col">
                                <input type="email" name="email" id="id_email" required />
                                <label for="id_email">Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-box col">
                                <input type="number" name="phone" id="id_phone" required />
                                <label for="id_phone">Phone</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-box col">
                                <textarea name="message" id="id_message" required></textarea>
                                <label for="id_message">Message</label>
                            </div>
                        </div>
                        <p class="d-flex mb-2" style="color: #0C1142;font-size: 10px;line-height: 18px">
                            <input type="checkbox" style="width: auto;margin-right: 5px;margin-top: 5px;" />By checking
                            this box, I agree
                            that
                            brandpulsar.com may
                            contact me from time to time at the email address above to tell me about its
                            services.
                        </p>
                        <input type="submit" class="btn-green btn-md" value="Send message" />
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="contact-info">
                    <ul>
                        <li class="email">
                            <h3>Drop Us an Email</h3>
                            <p>sales@brandpulsar.com</p>
                        </li>
                        <li class="faq">
                            <h3>Maybe we already have an answer</h3>
                            <a href="{% url 'main:faq' %}">
                                <p>Frequently Asked Questions</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/pages/favourites.html
{% extends 'base.html' %}
{% block meta %}
<title>{{ title }}</title>
<meta name="description" content="{{ meta_description }}" />
<meta property="og:title" content="{{ og_title }}" />
<meta property="og:type" content="{{ og_type }}" />
<meta property="og:url" content="{{ og_url }}" />
<meta property="og:image" content="{{ og_image }}" />
<meta property="og:description" content="{{ og_description }}" />
<meta property="og:site_name" content="{{ og_site }}" />
<meta name="robots" content="index, follow">
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{ og_title }}">
<meta name="twitter:image" content="{{ og_image }}">
<meta name="twitter:site" content="@Brand_Pulsar" />
<meta name="twitter:creator" content="@Brand_Pulsar" />
{% endblock meta %}
{% block content %}
{% load pagination_tags %}
{% load static %}
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="title mb-3 text-center">Your favorite domains</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="domaiajaxpast">
                    <div id="domainRow" class="row favorites">

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center" id="empty-message"></h1>
                <a href="{% url 'main:domains' %}" class="btn-green btn-md"
                    style="display: table;margin: 0px auto 0px auto;">Explore more domains</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

<!-- {% block extra_js %}
<script src="{% static 'js/favourites.js' %}" type="text/javascript"></script>
{% endblock %} -->