api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'domains/',
        views.DomainListView.as_view(),
        name="domain-list-api"),
    path(
        'my-domains/',
        views.UsersDomainsListView.as_view(),
        name="my-domain-list-api"),
    path(
        'brainstorming/',
        views.DomainBrainStormingAPIView.as_view(),
        name="brainstorming-api"
    ),
    path(
        'domains/<int:pk>/',
        views.SingleDomainAPIView.as_view(),
        name="single-domain-api"),
    path(
        'autocomplete/',
        views.SearchAutoCompleteView.as_view(),
        name="autocomplete-api"),
    path(
        'favourite/',
        views.FavouriteAPIView.as_view(),
        name="favourite-api"),
    path(
        'contacts/',
        views.ContactsAPIView.as_view(),
        name="contact-api"),
    path(
        'negotiate/',
        views.NegotiateContactAPIView.as_view(),
        name="negotiate-api"),
    path(
        'appraisal/',
        views.DomainAppraisalAPIView.as_view(),
        name="domain-appraisal"),
    path(
        'verify/',
        views.VerifyDomainAPIView.as_view(),
        name="verify-domain-redirect"
    ),
]

brandpulsar/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('v1/api/', include('rest_framework.urls')),
    path('v1/api/', include('api.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path
from . import views

app_name='marketplace'

urlpatterns = [
    path('become-a-seller/', views.BecomeASellerView.as_view(), name='become-a-seller'),
    path('create/', views.DomainCreateView.as_view(), name='create-domain'),
    path('setup/<int:pk>/', views.DomainSetupView.as_view(), name='setup-domain'),
    path('update/<int:pk>/', views.DomainUpdateView.as_view(), name='update-domain'),
    path('delete/<int:pk>/', views.DomainDeleteView.as_view(), name='delete-domain'),
    path('brainstorming/', views.BrainStormingView.as_view(), name="brainstorming-view"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register-view"),
    path('activate/', views.ActivateView.as_view(), name="register-done-view"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('activate/<uidb64>/<token>/',
         views.ActivateView.as_view(),
         name="activate-view"),
    path('login/', views.LoginView.as_view(), name="login-view"),
    path('logout/', views.LogOutView.as_view(), name="logout-view"),
    path(
        'password/reset/',
        views.CustomPasswordResetView.as_view(),
        name="password-reset"),
    path(
        'password/confirm/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm"),
    path(
        'password/done/',
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_complete"),
    path('edit/',
         login_required(views.UserEditView.as_view()),
         name="user-edit-view"),
    path('edit/password/',
         login_required(views.UserPasswordEditView.as_view()),
         name="user-edit-password-view"),
    # path(
    #     'payment-methods/',
    #     views.PaymentMethodListView.as_view(),
    #     name="payment-method-list"
    # ),
    # path(
    #    'add/payment-method/',
    #    views.PaymentMethodCreateView.as_view(),
    #    name="add-payment-method"
    # ),
    # path(
    #    'update/payment-method/<int:pk>/',
    #    views.PaymentMethodUpdateView.as_view(),
    #    name="update-payment-method"
    # ),
    # path(
    #    'delete/payment-method/<int:pk>/',
    #    views.PaymentMethodDeleteView.as_view(),
    #    name="delete-payment-method",
    # ),
    # path('payment-history/', views.PaymentHistoryView.as_view(),
    #      name="payment-history",)
]

users/models.py
from django.db import models

# Create your models here.

users/models/favourites.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model

User = get_user_model()


class Favourites(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="favourites",
        verbose_name = "Customer"
    )
    domains = models.ManyToManyField(
        "main.Domain",
        related_name='favourites',
        verbose_name = "Domain list",
        blank=True
    )

    class Meta:
        verbose_name = "Favourite"
        verbose_name_plural = "Favourites"
    
    def __str__(self):
        return f'{self.user} - favourites'

users/models/payment.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _

User = get_user_model()


class BasePayment(models.Model):
    email = models.EmailField()

    class Meta:
        abstract = True


class PayPalPayment(BasePayment):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="paypal_payment_methods"
    )
    class Meta:
        verbose_name = "PayPal Payment"
        verbose_name_plural = "PayPal Payment Methods"

    def __str__(self):
        return f"{self.user} - paypal payment method"


class CashAppPayment(BasePayment):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="cashapp_payment_methods"
    )
    class Meta:
        verbose_name = "CashAPP Payment"
        verbose_name_plural = "CashAPP Payment Methods"

    def __str__(self):
        return f"{self.user} - paypal payment method"


class SkrillPayment(BasePayment):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="skrill_payment_methods"
    )
    phone = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Skrill Payment"
        verbose_name_plural = "Skrill Payment Methods"

    def __str__(self):
        return f"{self.user} - paypal payment method"


class WirePayment(BasePayment):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="wire_payment_methods"
    )
    account_number = models.CharField(max_length=200)
    routing_number = models.CharField(max_length=200)
    holder_first_name = models.CharField(max_length=200)
    holder_last_name = models.CharField(max_length=200)
    iban = models.CharField(max_length=200)
    swift = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Wire Payment"
        verbose_name_plural = "Wire Payment Methods"

    def __str__(self):
        return f"{self.user} - wire payment method"

class PaymentHistory(models.Model):
    types = (
        ('paypal', _('PayPal')),
        ('cashapp', _('CashAPP')),
        ('skrill', _('Skrill')),
        ('wire', _('Wire')),
    )
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True
    )
    amount = models.DecimalField(
        _("Amount"),
        decimal_places=0, 
        max_digits=20, null=True
    )
    description = models.CharField(
        _("Description"),
        max_length=200,
        null=True, blank=True
    )
    method = models.CharField(choices=types, max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = _("Payment History")
        verbose_name_plural = _("Payment Histories")

    def __str__(self):
        return f'{self.user} - payment'

users/models/user.py
import random

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils.text import slugify
from brandpulsar.utils import compress_image


class UserManager(UserManager):
    """
    Manager for custom user model.
    """

    def create_user(self, email, password=None):
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)

        return user

    def _format_date_param(self, date):
        return date.replace("/", "-")


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model with email as main auth field.
    """
    GROUP_NAMES = ["New customer", "Elite user", "Standard user"]
    USER_TYPE = (
        (1, 'Buyer'), (2, 'Seller')
    )
    email = models.EmailField(verbose_name="Email", max_length=255, unique=True,)
    name = models.CharField(
        max_length=80,
        verbose_name="Name",
        blank=True, null=True
    )
    surname = models.CharField(
        max_length=80,
        verbose_name="Surname",
        blank=True, null=True
    )
    stripe_id = models.CharField(
        max_length=80,
        verbose_name="Stripe ID",
        blank=True, null=True
    )
    profile_picture = models.ImageField(
        upload_to="pp",
        verbose_name = "Profile Picture",
        null=True, blank=True
    )
    phone = models.CharField(
        max_length=80,
        verbose_name="Phone Number",
        blank=True, null=True
    )
    user_type = models.PositiveIntegerField(
        default=1,
        choices=USER_TYPE,
        verbose_name="User Type"
    )
    slug = models.SlugField(
        max_length=255, unique=True, 
        blank=True, editable=False
    )
    is_active = models.BooleanField(verbose_name="Active", default=False)
    is_staff = models.BooleanField(verbose_name="Staff", default=False)

    # Additional information
    current_sign_in_ip = models.GenericIPAddressField(
        blank=True, null=True, 
        verbose_name="Current IP"
    )
    last_signed_in_ip = models.GenericIPAddressField(
        blank=True, null=True, 
        verbose_name="Latest IP"
    )
    sign_in_count = models.IntegerField(
        default=0, verbose_name="Sign in count"
    )
    date_joined = models.DateTimeField(
        verbose_name="Joined on",
        auto_now_add=True,
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.name} {self.surname}"
    
    @property
    def total_domain_values(self):
        return sum([domain.price for domain in self.domains.all()])
    
    @property
    def sold_domain_count(self):
        return len([domain for domain in self.domains.all() if domain.status == 'sold'])
    
    @property
    def total_earned(self):
        return sum([domain.price for domain in self.domains.all() if domain.status == 'sold'])
    
    def generate_slug(self):
        slug = slugify(self.__str__())
        unique_slug = slug
        extension = 1
        while User._default_manager.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}{extension}"
            extension += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_slug()
        if self.profile_picture:
            self.profile_picture = compress_image(
                img=self.profile_picture,
                instance=self.__str__()
            )
        return super().save(*args, **kwargs)

users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm


User = get_user_model()


class RegisterForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, 
    from the given email and password.
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification."
    )

    class Meta:
        model = User
        fields = ['email', 'name', 'surname', 'phone']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2


class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'email-js',
                'id': 'modal-email',
                'placeholder': 'Enter your email'
            }))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'required-js',
                'id': 'modal-password',
                'placeholder': 'Enter your password'
            }))
    remember_me = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'id': 'modal-remember_me'
            }))

    error_messages = {
        'invalid_login': "*Please enter a correct email and password.\
                        Note that both fields may be case-sensitive.",
    }


class UserEditForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    name = forms.CharField(required=False)
    surname = forms.CharField(required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['email', 'name', 'surname', 'profile_picture']


class PasswordResetForm(forms.ModelForm):
    """ Custom Password Reset Form.
        Request object initialized for checking request.user
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'old_password_mismatch': "Old password value didn`t match",
    }
    old_password = forms.CharField()
    second_password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if check_password(old_password, self.request.user.password):
            return old_password
        else:
            raise forms.ValidationError(
                self.error_messages['old_password_mismatch'],
                code='password_mismatch',
            )

    def clean_second_password(self):
        password = self.cleaned_data.get("password1")
        second_password = self.cleaned_data.get("password2")
        if password and second_password and password != second_password:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return second_password


# class PaymentMethodForm(forms.ModelForm):
#    error_messages = {
#        'card_number_length': _("Card number length must be 16 characters"),
#        'card_number_error': _("Card number is not valid"),
#        'end_date_error': _("End date is not valid"),
#        'ccv_error': _("CCV is not valid"),
#    }
#    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
#    class Meta:
#        model=PaymentMethod
#        exclude=['user']
   
#    def clean_card_number(self):
#        card_number = self.cleaned_data.get('card_number')
#        if len(card_number) != 16:
#            print(f"Card number len {len(card_number)}")
#            raise forms.ValidationError(
#                self.error_messages['card_number_length']
#            )
#        try:
#            bool(int(card_number))
#        except:
#            raise forms.ValidationError(
#                self.error_messages['card_number_error']
#            )
#        return card_number
   
#    def clean_end_date(self):
#        end_date = self.cleaned_data.get('end_date')
#        if end_date < datetime.date.today():
#            raise forms.ValidationError(
#                self.error_messages['end_date_error'],
#                code='end_date_error'
#            )
#        return end_date
   
#    def clean_ccv_number(self):
#        ccv_number = self.cleaned_data.get('ccv_number')
#        if len(str(ccv_number)) != 3:
#            raise forms.ValidationError(
#                self.error_messages['ccv_error'],
#                code='ccv_error'
#            )
#        return ccv_number

templates/users/delete_payment_method.html
{% extends 'base.html' %}


{% block meta %}
<title>Brandpulsar | Delete Payment Method</title>
{% endblock meta %}

{% block content %}
{% load static %}
<section class="success-bg standard-bg">
    <div class="container">
        <div class="row mb-4 justify-content-center">
            <div class="col-md-6 col-12">
                <h2 class="text-white text-center pb-3">Delete Payment Method</h2>
                <form method="POST">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    {{form.as_p}}
                    <div class="form-group">
                        <button class="btn btn-main" type="submit">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}


{% block meta %}
<title>Brandpulsar | Login</title>
{% endblock meta %}

{% block content %}
{% load static %}
<style>
    .header-nav,
    .footer {
        display: none;
    }
</style>
<section class="auth-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="auth-container">
                    <a href="{% url 'main:index' %}" class="auth-badge">
                        <img src="{% static 'images/cosmic-icon-tr.svg' %}" />
                    </a>
                    <div class="auth-image">

                    </div>
                    <div class="auth-content">
                        <a href="{% url 'main:index' %}" class="purple-back-btn mb-3"><img
                                src="{% static 'images/left-arrow-2.svg' %}">Back to home
                            page</a>
                        <h1 class="pb-3">Login to your account</h1>
                        <form method="POST">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}

                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endif %}

                            <div class="row">
                                <div class="input-box col">
                                    <input type="email" name="username" id="modal-email" required />
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="password" id="modal-password" required />
                                    <label for="password1">Password</label>
                                </div>
                            </div>
                            <p class="d-flex mb-2" style="color: #0C1142;font-size: 10px;line-height: 18px">
                                <input type="checkbox" name="remember_me" id="modal-remember_me"
                                    style="width: auto;margin-right: 5px;margin-top: 5px;" />Remember me
                            </p>

                            <div class="form-group">
                                <button class="btn-green btn-md" style="width: 100%;" type="submit">Log in</button>
                            </div>
                        </form>
                        <p style="display: flex;align-items: center;justify-content: space-between;">
                            <a href="{% url 'users:register-view' %}">Not a member yet?</a>
                            <a href="{% url 'users:password-reset' %}">Forget Password?</a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/users/password-reset.html
{% extends 'base.html' %}

{% block meta %}
<title>Brandpulsar | Reset your password</title>
{% endblock meta %}

{% block content %}
{% load static %}
<section class="success-bg standard-bg">
    <div class="container">
        <div class="row mb-4 justify-content-center">
            <div class="col-md-6 col-12">
                <h2 class="text-white text-center pb-3">Reset your password</h2>

                <div class="d-flex align-items-center justify-content-center">
                    <a class="text-white" href="{% url 'users:login-view' %}">Sign in</a>
                    <span class="text-white pl-1 pr-1">|</span>
                    <a class="text-white" href="{% url 'users:register-view' %}">Sign up</a>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Brandpulsar | Registration</title>
{% endblock meta %}

{% block content %}
{% load static %}
<style>
    .header-nav,
    .footer {
        display: none;
    }
</style>
<section class="auth-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="auth-container">
                    <a href="{% url 'main:index' %}" class="auth-badge">
                        <img src="{% static 'images/cosmic-icon-tr.svg' %}" />
                    </a>
                    <div class="auth-image">
                        <div class="title">
                            <h1>Register to buy or sell premium domains</h1>
                        </div>
                    </div>
                    <div class="auth-content">
                        <a href="{% url 'main:index' %}" class="purple-back-btn mb-3"><img
                                src="{% static 'images/left-arrow-2.svg' %}">Back to
                            home
                            page</a>
                        <form method="POST">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endif %}
                            <div class="row">
                                <div class="input-box col">
                                    <input type="text" name="name" id="id_name" required />
                                    <label for="name">First name</label>
                                </div>
                                <div class="input-box col">
                                    <input type="text" name="surname" id="id_surname" required />
                                    <label for="surname">Last name</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="email" name="email" id="id_email" required />
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="number" name="phone" id="id_phone" required />
                                    <label for="phone">Phone</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="password1" id="id_password1" required />
                                    <label for="password1">Password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="password2" id="id_password2" required />
                                    <label for="password2">Password confirmation</label>
                                </div>
                            </div>
                            <p class="d-flex mb-2" style="color: #0C1142;font-size: 10px;line-height: 18px">
                                <input type="checkbox" style="width: auto;margin-right: 5px;margin-top: 5px;" />By
                                checking
                                this box, I agree
                                that
                                brandpulsar.com may
                                contact me from time to time at the email address above to tell me about its
                                services.
                            </p>
                            <input type="submit" class="btn-green btn-md" value="Get an account" />
                            <p style="color: #0C1142;text-align: center;font-size: 10px;line-height: 18px">By submitting
                                this form I have read
                                and acknowledged the <a href="#">Privacy
                                    Policy</a>.
                            </p>
                            <p style="color: #0C1142;text-align: center;font-size: 10px;line-height: 18px">Already
                                registered? <a href="{% url 'users:login-view' %}">Log in</a>.
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/users/user_edit_password.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Brandpulsar | Password update: {{request.user.email}}</title>
{% endblock meta %}

{% block content %}
<style>
    .header-nav,
    .footer {
        display: none;
    }
</style>
<section class="auth-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="auth-container">
                    <div class="auth-content form-box" style="overflow-y: scroll;width: 100%;">
                        <h1 class="text-center pb-3">Update your password</h1>


                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endif %}
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="old_password" id="id_old_password" maxlength="255"
                                        required>
                                    <label for="id_old_password">Current password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="password" id="id_password" maxlength="255" required>
                                    <label for="id_password">New Password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-box col">
                                    <input type="password" name="second_password" id="id_second_password" required>
                                    <label for="id_second_password">Verify Password</label>
                                </div>
                            </div>

                            <a href="{% url 'users:user-edit-view' %}" class="btn-white btn-md">Cancel</a>
                            <button class="btn-green btn-md" type="submit">Update</button>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}